# 1. 넘파이

다양한 행렬 연산을 지원한다.

1차원 배열은 벡터(vector), 2차원 배열은 행렬(matrix). 벡터와 행렬을 일반화한 것을 텐서(tesor)라고 한다.

In [1]:
import numpy as np

# 행렬의 선언과 곱
a = np.array([[1, 2], [3, 4]])
b = np.array([1, 2])

c = b * a
print(c)

[[1 4]
 [3 8]]


## 1-1. 브로드캐스트
넘파이에서는 다른 형태의 행렬끼리 연산을 지원한다. 이를 브로드캐스트라고 한다.

In [8]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
print (4 * a)

# 2x2행렬과 연산할 수 있도록 c를 아래로 늘린다.
b = np.array([[1, 2, 3], [3, 4, 4], [5, 6, 7]])
c = np.array([4, 5, 6])  # c = np.array([4, 5])은 에러가 뜬다 (ValueError: operands could not be broadcast together with shapes (3,3) (2,) )
print( b * c)

[[ 4  8]
 [12 16]]
[[ 4 10 18]
 [12 20 24]
 [20 30 42]]


## 1-2. 인덱싱

In [10]:
import numpy as np

a = np.array([[1, 2, 3], [3, 3, 3], [5, 5, 5], [12, 3, 6]])

# for문을 통한 행 접근
for row in a :
    print(row)

# 원소 또는 행 인덱싱
print(a[1]) # 행 접근
print(a[3][1]) # 원소 접근

[1 2 3]
[3 3 3]
[5 5 5]
[12  3  6]
[3 3 3]
3
